FROM resin/rpi-raspbian:latest
COPY . /project
WORKDIR /project
RUN echo "deb http://mirrordirector.raspbian.org/raspbian/ stretch main contrib non-free rpi" > /etc/apt/sources.list
RUN apt-get update
RUN apt-get install python3 python3-pip python3-setuptools python3-gpiozero
RUN pip3 install -r requirements.txt
EXPOSE 3000
CMD ["python3", "app/app.py"]
